services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./backend:/app
      - /app/go
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - GIN_MODE=debug
      - ENV=development
      - LOG_REQUESTS=true
      - LOG_SQL=false
      - LOG_CORS=false
      - BACKEND_HOST=0.0.0.0
      - DB_PATH=/app/data/finance.db
    networks:
      - ${DOCKER_NETWORK:-finance-network}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - ${DOCKER_NETWORK:-finance-network}

networks:
  finance-network:
    driver: bridge 